version: '3.7'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn web.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    networks:
      - service_network
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    networks:
      - service_network
    depends_on:
      - web
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=simprolix
      - POSTGRES_PASSWORD=pass@123
      - POSTGRES_DB=simprolix
    ports:
      - 5433:5432
    env_file:
      - ./.env.prod.db
    networks:
      - service_network
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume:
networks:
  service_network:
    driver: bridge
